language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

cache:
  directories:
     - vendor

install:
   - rm composer.lock
   - composer install

script:
   - vendor/bin/phpunit --coverage-clover=coverage.xml --verbose tests

after_success:
   - bash <(curl -s https://codecov.io/bash)
