language: php
dist: trusty

php:
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'
  - '5.5'

cache:
  directories:
     - $COMPOSER_CACHE_DIR

install:
   - rm composer.lock
   - composer install

script:
   - vendor/bin/codecept run --verbose --coverage --coverage-xml --coverage-html

after_success:
   - bash <(curl -s https://codecov.io/bash)

env:
  global:
     - COMPOSER_CACHE_DIR="$HOME/.cache/composer"
